CREATE TABLE MENIURI (
COD_PRODUS NUMBER(6) PRIMARY KEY,
DENUMIRE VARCHAR2(50),
CATEGORIE VARCHAR2(30),
PRET NUMBER(6, 2),
DISPONIBILITATE VARCHAR2(10));

CREATE TABLE CLIENTI (
COD_CLIENT NUMBER(6) PRIMARY KEY,
NUME VARCHAR2(30),
PRENUME VARCHAR2(30),
TELEFON VARCHAR2(15),
ADRESA VARCHAR2(50),
EMAIL VARCHAR2(50));

CREATE TABLE COMENZI (
COD_COMANDA NUMBER(6) PRIMARY KEY,
COD_CLIENT NUMBER(6),
DATA_COMANDA DATE,
COST_TOTAL NUMBER(8, 2),
CONSTRAINT comanda_fk FOREIGN KEY(COD_CLIENT) REFERENCES CLIENTI(COD_CLIENT));

CREATE TABLE DETALII_COMENZI (
COD_DETALIU NUMBER(6) PRIMARY KEY,
COD_COMANDA NUMBER(6),
COD_PRODUS NUMBER(6),
CANTITATE NUMBER(3),
PRET_UNITAR NUMBER(6, 2),
CONSTRAINT detalii_comanda_fk1 FOREIGN KEY(COD_COMANDA) REFERENCES COMENZI(COD_COMANDA),
CONSTRAINT detalii_comanda_fk2 FOREIGN KEY(COD_PRODUS) REFERENCES MENIURI(COD_PRODUS));

CREATE TABLE FACTURI (
COD_FACTURA NUMBER(6) PRIMARY KEY,
COD_COMANDA NUMBER(6),
DATA_EMITERE DATE,
SUMA_TOTALA NUMBER(8, 2),
CONSTRAINT factura_fk FOREIGN KEY(COD_COMANDA) REFERENCES COMENZI(COD_COMANDA));

CREATE TABLE REZERVARI (
COD_REZERVARE NUMBER(6) PRIMARY KEY,
COD_CLIENT NUMBER(6),
DATA_REZERVARE DATE,
NR_PERSOANE NUMBER(2),
CONSTRAINT rezervare_fk FOREIGN KEY(COD_CLIENT) REFERENCES CLIENTI(COD_CLIENT));

CREATE TABLE PLATI (
COD_PLATA NUMBER(6) PRIMARY KEY,
COD_COMANDA NUMBER(6),
DATA_PLATA DATE,
METODA_PLATA VARCHAR2(20),
SUMA NUMBER(8, 2),);

ALTER TABLE PLATI ADD CONSTRAINT plata_fk FOREIGN KEY (COD_COMANDA) REFERENCES COMENZI(COD_COMANDA);

DROP TABLE REZERVARI;
FLASHBACK TABLE REZERVARI TO BEFORE DROP;